compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: /home/winnie/halos/trl/deepspeed_config.json # /env/lib/repos/gbm/core/experimental/gbm/deepspeed_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
# machine_rank: 0
# main_process_ip: null
# main_process_port: null
main_training_function: main
num_machines: 4
num_processes: 32
use_cpu: false
